### ISSUE TITLE
Testing decryptFRAM

### ISSUE THREAD

**Issue by cryptax** [ivalkou/LibreTools#1]
Hi, 
In Libre2.swift, you provide encrypted test example for Libre 2. For example,

```
enum Example2 {
        static let sensorInfo: [UInt8] = [0x9D, 0x08, 0x30, 0x01, 0x76, 0x25]

        static let sensorId: [UInt8] = [0xDF, 0x20, 0xBE, 0x00, 0x00, 0xA4, 0x07
, 0xE0]

        static let buffer: [UInt8] = [
            0x52, 0x0B, 0xF3, 0x44, 0xDC, 0xA0, 0x43, 0x21,
            0xCC, 0x7D, 0xD7, 0x4E, 0x29, 0xE2, 0x82, 0xE3,
```

Is it possible that you supply the expected output of `decryptFRAM` for that? Would help ensure your code does not have regression, and that my own code (writing a Python version of decryptFRAM) works :=)

Thanks,

**Comment by cryptax** [comment]
don't worry too much, I figured it out :+1:  but it might be helpful to you indeed to include the decryption and test against it.

**Comment by JtxGit** [comment]
Hi
Since I am busy porting this part of LibreTools to Kotlin, it would be great to have a confirmed correct expected output. 
Thanks in advance!

**Comment by JtxGit** [comment]
This is what I'm getting:

ID2: [223, 32, 190, 0, 0, 164, 7, 224]
ID2: df20be0000a407e0
Info2: [157, 8, 48, 1, 118, 37]
Info2: 9d0830017625
Data in: 520bf344dca04321cc7dd74e29e282e3e704c9cf6c572c7da88210aad73219b3c79f395fe37a4508b709bc6efada3407b46568607ea504e665654813f89ca7c870a74d9d523586f202cc9b9b7432ffc5bfe9781f46c2c70b0fb0c85423e20d449744368fac12ae4a6ce137e2462b5c741b7afe674fccdd951773b325e9aba65e70e46cce568db9e5feaa503652d2c5222439d863086204adfa89001072cfa9f3474bf57096f28acaffefa39e1aec9f4a2fe8a9cae6c8744698b2a29e8df0af09c15b52597e00d33f59417b33eedb4051b23d9482f3b2e4caad3cd8c0d7d74c51caa3ad2624ab10ba6135e17f3d3fecb4cfe3a2316ae7d73618215b435a9c757c89e2496cb1716a476e8ae5b2c537e9e5ddb31237957ad01f73ebb815f1e65d51fb1688a69c17b0400ebbd7ca9dcd8b60888854fc657143e751e218ea631d5baad1d3d708b7ed87c4b42431e7a0e6595193fda3e6bfe1f209
Data out: 815a101c030000000000000000000000000000000000000008da0213480500849600430500b896008305005c96008305005c96007505006496006d05005c960072050068d6007d05005c96007705005096006b05004096006105003896006905083696006505003496005105002496004b05003496004e0500509600c30700849600210800d4d500f10600d496006f0500ec9600890500149900950500c89800d505088698007106083298009b06008c5800d00600585800a80600249800b605002898001705000c9800f10400dc97005805003458009d05005897008f0500d496008a05008c96005805003496000e04089e5800c303000098007a0400189700f80400c89700420400409800150400649800710400fc97007104005097002f04083e58008604082a9800c10408c657009e06006097002c0700309700620c010071c63001ca091751140396805a00cda618a31a0000b2c860
