### ISSUE TITLE
Inferring Glucose reading

### ISSUE THREAD

**Issue by deepakthakur143** [ivalkou/LibreTools#3]
Though I can see from the code how the Trend and History segments are identified, but it is not clear how the Glucose reading is derived from the trend data. Please help.

**Comment by ivalkou** [comment]
@deepakthakur143  This data is for technical use only. The program is not designed to read glucose values. BG is dependent on calibrations, which not included in this program. You can use history and trend to understand if a sensor is working properly.

**Comment by deepakthakur143** [comment]
One more thing @ivalkou, I am working on LibrePro, and looks like most of the history section is locked/protected, and hence not able to read. I am able to read only 256 blocks (8 bytes/block), which is the trend section and 3 days' worth of history section. Any idea how to read the rest of the history section.
